services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./data:/config
      - ${DOWNLOADS}:/downloads
      - ${MEDIA}:/media
    ports:
      - "8989:8989"
    restart: unless-stopped

include:
  - ../network.yaml