services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    network_mode: container:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    restart: unless-stopped