services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    network_mode: container:gluetun
    mem_limit: 1024M
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - autoheal=true
      - autoheal.stop.timeout=30
