services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped