services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    networks:
      arr_net:
        ipv4_address: 172.23.0.13
      proxy:
    mem_limit: 1024M
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.whisparr.entrypoints=http"
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.${DOMAIN}`)"
      - "traefik.http.middlewares.whisparr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.whisparr.middlewares=whisparr-https-redirect"
      - "traefik.http.routers.whisparr-secure.entrypoints=https"
      - "traefik.http.routers.whisparr-secure.rule=Host(`whisparr.${DOMAIN}`)"
      - "traefik.http.routers.whisparr-secure.tls=true"
      - "traefik.http.routers.whisparr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.whisparr-secure.service=whisparr"
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"

      - autoheal=true
      - autoheal.stop.timeout=30

networks:
  proxy:
    external: true
  arr_net:
    external: true