services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    network_mode: container:gluetun
    mem_limit: 1024M
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    labels:
      autoheal: true
    restart: unless-stopped