services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata/config:/config
      - ./appdata/data:/data
      - ${MEDIA}:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped