services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    networks:
      arr_net:
        ipv4_address: 172.18.0.8
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA}:/media
    restart: unless-stopped

include:
  - ../network.yaml