services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - arr_net
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./prowlarr/data:/config
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
      - C:/Users/LS/Videos/Torrents:/media
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./radarr/data:/config
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
      - C:/Users/LS/Videos/Torrents:/media
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/data:/config
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
      - C:/Users/LS/Videos/Torrents:/media
    ports:
      - "8989:8989"
    restart: unless-stopped

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    networks:
      - arr_net
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ./whisparr/config:/config
      - ./whisparr/data:/data
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
      - C:/Users/LS/Videos/Torrents:/media
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./readarr/data:/config
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
      - C:/Users/LS/Book:/book
    ports:
      - "8787:8787"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/appdata:/config
      - C:/Users/LS/Videos/Torrents/Downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

networks:
  arr_net:
    driver: bridge
