services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.23.0.3
      proxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "85:80/tcp"
      - "445:443/tcp"
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      PIHOLE_DNS_: 172.23.0.4#5053
    volumes:
      - ./etc-pihole:/etc/pihole
    restart: unless-stopped

networks:
  proxy:
    external: true
  dns_net:
    external: true