services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks:
      arr_net:
        ipv4_address: 172.18.0.6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./appdata:/config
      - ${MEDIA}:/media
    ports:
      - "8787:8787"
    restart: unless-stopped

include:
  - ../network.yml