services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./appdata/config:/config
      - ./appdata/cache:/cache
      - ${MEDIA}:/media
    restart: 'unless-stopped'