services:
  jellysearch:
    image: domistyle/jellysearch
    restart: unless-stopped
    networks:
      proxy:
    volumes:
      - /opt/jellysearch/config:/config:ro
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      INDEX_CRON: "0 0 0/2 ? * * *"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.jellysearch.loadbalancer.server.port=5000"
      - "traefik.http.routers.jellysearch.rule=Host(`jellyfin.${DOMAIN}`) && (QueryRegexp(`searchTerm`, `(.*?)`) || QueryRegexp(`SearchTerm`, `(.*?)`))"

networks:
  proxy:
    external: true