services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - arr_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./data:/config
      - ${DOWNLOADS}:/downloads
      - ${MEDIA}:/media
    ports:
      - "7878:7878"
    restart: unless-stopped

include:
  - ../network.yaml