services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    networks:
      arr_net:
        ipv4_address: 172.18.0.5
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/config
      - ${MEDIA}:/media
    ports:
      - "8090:8090"
    restart: unless-stopped


include:
  - ../network.yaml