services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:arm64v8-latest
    container_name: tvheadend
    mem_limit: 1024M
    networks:
      proxy:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /opt/tvheadend/data:/config
      - /opt/tvheadend/recordings:/recordings
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9981/" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tvheadend-secure.entrypoints=https"
      - "traefik.http.routers.tvheadend-secure.rule=Host(`tvheadend.${DOMAIN}`)"
      - "traefik.http.routers.tvheadend-secure.tls=true"
      - "traefik.http.routers.tvheadend-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.tvheadend-secure.service=tvheadend"
      - "traefik.http.services.tvheadend.loadbalancer.server.port=9981"

networks:
  proxy:
    external: true