services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    expose:
      - "53"
    networks:
      dns_net:
        ipv4_address: 172.23.0.4
    volumes:
      - /opt/unbound/etc/unbound:/opt/unbound/etc/unbound
      - /opt/unbound/etc/unbound/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf
      - /opt/unbound/etc/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf
      - /opt/unbound/etc/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped

networks:
  dns_net:
    external: true