services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata:/config
      - ${MEDIA}:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped