---
services:
  restic:
    extends:
      file: ../common.yml
      service: common-config
    image: restic/rest-server:0.14.0
    container_name: restic
    environment:
      - DISABLE_AUTHENTICATION=1
      - OPTIONS=--append-only --private-repos --listen :8000
    networks:
      - proxy
    volumes:
      - /opt/backups/restic:/data
networks:
  proxy:
    external: true
