# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
---
sonarr:
  series:
    base_url: http://sonarr:8989
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: 58e8dc75731040612dd6f4ac0676bfd7 # [French MULTi.VF] HD Bluray + WEB (1080p)
        name: FC Shared FR-MULTi.VF HD
        reset_unmatched_scores:
          enabled: true
      - trash_id: 68c8b82ad2b7ea1941fce71eb56421c3 # [French MULTi.VF] UHD Bluray + WEB (2160p)
        name: FC Shared FR-MULTi.VF UHD
        reset_unmatched_scores:
          enabled: true
      - trash_id: 4c48f506c1116a3a57ae33f12346bd15 # [French MULTi.VO] HD Bluray + WEB (1080p)
        name: FC Personal FR-MULTi.VO HD
        reset_unmatched_scores:
          enabled: true
      - trash_id: 6fa7364373e8f06206871d9c20a4fb3e # [French MULTi.VO] UHD Bluray + WEB (2160p)
        name: FC Personal FR-MULTi.VO UHD
        reset_unmatched_scores:
          enabled: true
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        name: FC Anime 1080p
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: 158188097a58d7687dee647e04af0da3 # [Required] Golden Rule HD
          select:
            - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        - trash_id: e3f37512790f00d0e89e54fe5e790d1c # [Required] Golden Rule UHD
          select:
            - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
    custom_formats:
      - trash_ids:
          - 2c29a39a4fdfd6d258799bc4c09731b9 # VFF
          - 34789ec3caa819f087e23bbf9999daf7 # VF2
        assign_scores_to:
          - name: FC Shared FR-MULTi.VF HD
            score: 25
          - name: FC Shared FR-MULTi.VF UHD
            score: 25
          - name: FC Personal FR-MULTi.VO HD
            score: 25
          - name: FC Personal FR-MULTi.VO UHD
            score: 25
      - trash_ids:
          - 7a7f4e4f58bd1058440236d033a90b67 # VFQ
        assign_scores_to:
          - name: FC Shared FR-MULTi.VF HD
            score: -25
          - name: FC Shared FR-MULTi.VF UHD
            score: -25
          - name: FC Personal FR-MULTi.VO HD
            score: -25
          - name: FC Personal FR-MULTi.VO UHD
            score: -25
