services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./appdata:/gluetun
    ports:
      - "6767:6767" # bazarr
      - "5454:5454" # notifiarr
      - "9696:9696" # prowlarr
      - "7878:7878" # radarr
      - "8989:8989" # sonarr
      - "6969:6969" # whisparr
      - "8191:8191" # flaresolverr
      - "5055:5055" # jellyseerr
      - "8081:8081" # qbittorrent web interface
      - "6881:6881" # qbittorrent torrent port
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped